### ISSUE TITLE
map conversion error (affected all maps)

### ISSUE THREAD

**Issue by sbrstrkkdwmdr** [kotritrona/osumapper#18]
Number of filtered maps: 11
Error: ENOENT: no such file or directory, open '#C:\Users\saber\AppData\Local\osu!\Songs\1232750 Kagetora - Crazy banger\Kagetora. - Crazy banger (waywern2012) [PENGUINS].osu'
    at Object.openSync (node:fs:495:3)
    at Object.readFileSync (node:fs:396:35)
    at main (c:\Users\saber\Desktop\osumapper-master\osumapper-master\v7.0\load_map.js:1395:26)
    at Object.<anonymous> (c:\Users\saber\Desktop\osumapper-master\osumapper-master\v7.0\load_map.js:1484:1)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: '#C:\\Users\\saber\\AppData\\Local\\osu!\\Songs\\1232750 Kagetora - Crazy banger\\Kagetora. - Crazy banger (waywern2012) [PENGUINS].osu'
}

Error on #0, path = #C:\Users\saber\AppData\Local\osu!\Songs\1232750 Kagetora - Crazy banger\Kagetora. - Crazy banger (waywern2012) [PENGUINS].osu, error = Map Convert Failure

**Comment by sbrstrkkdwmdr** [comment]
oh wait nvm fixed it just removed the #

**Comment by sbrstrkkdwmdr** [comment]
oh wait nvm fixed it just remove the #
